# Configuration file for the project (sulfidic-fish-genome-assembly).

# Define the absolute path to the working directory.
working_directory: '/Users/emanuelmfonseca/Downloads/sulfidic-fish-genome-assembly'

# number of CPUs available for analysis
ncpus: 6

# Define the path to fastq-dump
fastq_dump_path: 'Softwares/sratoolkit/bin/fastq-dump'
